### ISSUE TITLE
apply simple layout option when adding new nodes

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer_web#4]
A new user who has figured out how to add a new node and then clicks that node will see this:

![2017-05-25_15-43-10](https://cloud.githubusercontent.com/assets/2635409/26473577/240a83e0-4161-11e7-959d-32bf951143f4.png)

This layout is rather confusing.  Apply some layout function to separate the nodes.

**Comment by kevinxin90** [comment]
Issue fixed by changing layout option from 'cose' to 'concentric'. In 'cose' layout, it automatically put nodes in a line.
[commit](https://github.com/biothings/biothings_explorer_web/commit/47aed73a19bc564a402fde7dbb9b02d8ceba25f0)
