### ISSUE TITLE
Extra prefix in `json["data"]["target"]`

### ISSUE THREAD

**Issue by erikyao** [biothings/biothings_explorer_web#43]
Hi Kevin, 

MWE: [http://biothings.io/explorer/api/v2/directinput2output?input_prefix=do&output_prefix=hp&input_value=1498](http://biothings.io/explorer/api/v2/directinput2output?input_prefix=do&output_prefix=hp&input_value=1498)

The `json["data"]["target"]` field is like `"hp:HP:0002090"`, which used to be `"HP:0002090"`.

Similarly I am getting IDs like `"HGNC:HGNC:11138"` and `"UBERON:UBERON:0002113"`. Could you please check it out?

Thanks!
Yao

**Comment by kevinxin90** [comment]
I think I know where the problem comes from! It's related to the fix I did for JSON-LD ":". I will work on it! Thanks for letting me know!

**Comment by erikyao** [comment]
Thank you, Kevin! You are so responsive! Have a good weekend!
