### ISSUE TITLE
Extra space in pubchem.compound ID

### ISSUE THREAD

**Issue by erikyao** [biothings/biothings_explorer_web#44]
Hi Kevin, 

MWE: [http://biothings.io/explorer/api/v2/directinput2output?input_prefix=chembl.compound&output_prefix=pubchem.compound&input_value=CHEMBL503](http://biothings.io/explorer/api/v2/directinput2output?input_prefix=chembl.compound&output_prefix=pubchem.compound&input_value=CHEMBL503)

There are `json["data"]["output"]["object"]["id"]` fields containing spaces, like `"PUBCHEM.COMPOUND:SID: 26697338"`.

Is it on purpose or an error? Thanks!

Best,
Yao

**Comment by kevinxin90** [comment]
Hi Yao, I will look into it. This is indeed an error from mychem.info, which is also part of our group's project. When integrating multiple different resources into mychem.info, some data discrepancy issue occurred. The quick solution is I will change the JSON-LD context file for MyChem, so only the correct ID will return. But in the long run, we will fix the problem in MyChem.info. Thanks for letting me know!

**Comment by erikyao** [comment]
Thank you, Kevin!

**Comment by kevinxin90** [comment]
@erikyao Hi Yao, I made a quick fix on the JSON-LD file for MyChem.info, so now it should work for your purpose. I have also created an issue ticket on [MyChem.info github repo](https://github.com/biothings/mychem.info/issues/20). We will fix it in the source API soon. Thanks again!

**Comment by erikyao** [comment]
Test passed. Thank you for the quick fix!
