### ISSUE TITLE
incorrect URL when querying myvariant.info

### ISSUE THREAD

**Issue by andrewsu** [biothings/biothings_explorer_web#5]
Load CDK2 (entrez gene 1017), then click myvariant.info.  biothings explorer reports no variants found.  That's because it is querying this URL

http://myvariant.info/v1/query?q=clinvar.gene.id:1017%20OR%20emv.gene.id:1017%20OR%20dbsnp.gene.geneid

when it should be querying this URL

http://myvariant.info/v1/query?q=clinvar.gene.id:1017%20OR%20emv.gene.id:1017%20OR%20dbsnp.gene.geneid:1017

**Comment by kevinxin90** [comment]
This one is fixed now both in python client and in the biothings browser.
